# Generated by Django 2.1.4 on 2019-01-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0013_auto_20190130_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
